#!/usr/bin/env bash

if
  [[ -s "/home/oksana/.rvm/gems/ruby-2.7.1/environment" ]]
then
  source "/home/oksana/.rvm/gems/ruby-2.7.1/environment"
  exec bundler "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/oksana/.rvm/gems/ruby-2.7.1/environment'" >&2
  exit 1
fi
