#!/usr/bin/env bash

if
  [[ -s "/home/oksana/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/environment" ]]
then
  source "/home/oksana/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/environment"
  exec bundle "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/oksana/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/environment'" >&2
  exit 1
fi
